Feature: Product Page - Roller Theme
#prod_sbase_roller_product_page
#  staging_sbase_roller_product_page
#  dev_sbase_roller_product_page

  Background:
    Given user login to shopbase dashboard by API
    When user navigate to "Online Store" screen
    And user click Customize on current theme
    And choose preview page "Homepage"

  Scenario Outline: Verify Feature product and Product page #SB_OLS_THE_ROL_56 #SB_OLS_THE_ROL_57 #SB_OLS_THE_ROL_58 #SB_OLS_THE_ROL_59 #SB_OLS_THE_ROL_60 #SB_OLS_THE_ROL_61 #SB_OLS_THE_ROL_62
    And change Feature product settings as "<KEY>"
      | KEY | Product name        | Show arrows on product gallery | Enable product gallery slideshow | Gallery transition | Image position | Show vendor | Show price savings | Show product content |
      | 1   | MC White Lace Dress | false                          | false                            | Fade               | Left           | false       | false              | false                |
      | 2   | MC White Lace Dress | true                           | true                             | Slide              | Right          | true        | true               | true                 |
      | 3   | MC White Lace Dress | true                           | true                             | Slide              | Right          | true        | true               | true                 |
    And change Product page settings as "<KEY>"
      | KEY | Enable product gallery popup | Show breadcrumb links | Show vendor | Show SKU | Show price savings | Show collections | Show types | Show tags | Show social media share icons | Show Sticky button |
      | 1   | false                        | false                 | false       | false    | false              | false            | false      | false     | false                         | false              |
      | 2   | true                         | true                  | true        | true     | true               | true             | true       | true      | true                          | true               |
      | 3   | true                         | true                  | true        | true     | true               | true             | true       | true      | true                          | true               |
    And change Product grid setting as "<KEY>"
      | KEY | Show sale banners | Options style        | Enable variant group swatches | Enable color swatches | Hide selector when option has one value | Show quantity box | Show quantity box in the same line | Link product options                                                        | Select variants by clicking their images | Show trust badge image | Show countdown timer | Text for 0$ product | Tab position |
      | 1   | false             | Select dropdown list | false                         | false                 | false                                   | false             | false                              | Link product options, only show available combination                       | false                                    | false                  | false                | Free                | Bottom       |
      | 2   | true              | Buttons              | false                         | false                 | true                                    | true              | false                              | Make all choices in all drop-downs available, even out of stock combination | true                                     | true                   | true                 |                     | Right        |
      | 3   | true              | Buttons              | true                          | true                  | true                                    | true              | true                               | Make all choices in all drop-downs available, even out of stock combination | true                                     | true                   | true                 | Free                | Bottom       |
    Then open shop on storefront
    And verify Feature product settings as "<KEY>"
      | KEY | Product name        | Show arrows on product gallery | Enable product gallery slideshow | Gallery transition | Image position | Show vendor | Show price savings | Show product content | Show sale banners | Options style        | Enable variant group swatches | Enable color swatches | Hide selector when option has one value | Show quantity box | Show quantity box in the same line | Link product options                                                        | Select variants by clicking their images | Show countdown timer | Text for 0$ product | Tab position |
      | 1   | MC White Lace Dress | false                          | false                            | Fade               | Left           | false       | false              | false                | false             | Select dropdown list | false                         | false                 | false                                   | false             | false                              | Link product options, only show available combination                       | false                                    | false                | Free                | Bottom       |
      | 2   | MC White Lace Dress | true                           | true                             | Slide              | Right          | true        | true               | true                 | true              | Buttons              | false                         | false                 | true                                    | true              | false                              | Make all choices in all drop-downs available, even out of stock combination | true                                     | true                 |                     | Right        |
      | 3   | MC White Lace Dress | true                           | true                             | Slide              | Right          | true        | true               | true                 | true              | Buttons              | true                          | true                  | true                                    | true              | true                               | Make all choices in all drop-downs available, even out of stock combination | true                                     | true                 | Free                | Bottom       |
    And verify product page setting as "<KEY>"
      | KEY | Product             | Enable product gallery popup | Show breadcrumb links | Show vendor | Show SKU | Show price savings | Show collections | Show types | Show tags | Show social media share icons | Show Sticky button | Show sale banners | Options style        | Enable variant group swatches | Enable color swatches | Hide selector when option has one value | Show quantity box | Show quantity box in the same line | Show trust badge image | Link product options                                                        | Select variants by clicking their images | Show countdown timer | Text for 0$ product | Tab position |
      | 1   | MC White Lace Dress | false                        | false                 | false       | false    | false              | false            | false      | false     | false                         | false              | false             | Select dropdown list | false                         | false                 | false                                   | false             | false                              | false                  | Link product options, only show available combination                       | false                                    | false                | Free                | Bottom       |
      | 2   | MC White Lace Dress | true                         | true                  | true        | true     | true               | true             | true       | true      | true                          | true               | true              | Buttons              | false                         | false                 | true                                    | true              | false                              | true                   | Make all choices in all drop-downs available, even out of stock combination | true                                     | true                 |                     | Right        |
      | 3   | MC White Lace Dress | true                         | true                  | true        | true     | true               | true             | true       | true      | true                          | true               | true              | Buttons              | true                          | true                  | true                                    | true              | true                               | true                   | Make all choices in all drop-downs available, even out of stock combination | true                                     | true                 | Free                | Bottom       |
    And quit browser
    Examples:
      | KEY |
      | 1   |
      | 2   |
      | 3   |
